# Generated by Django 4.1.7 on 2023-03-24 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userpersonalinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
