# Generated by Django 4.1.7 on 2023-04-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersbackupcodes',
            name='codes_file',
            field=models.FileField(default=None, null=True, upload_to='codes/%Y-%m-d/'),
        ),
    ]
