# Generated by Django 4.1.7 on 2023-05-12 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_settings', '0003_alter_usersbackupcodes_codes_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPITokens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField()),
                ('token_opportunity', models.CharField(choices=[('1', 'Create TinyURL'), ('2', 'UpdateTinyURL'), ('3', 'Archive TinyURL')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
