# Generated by Django 4.1.7 on 2023-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0004_userapitokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapitokens',
            name='token_opportunity',
        ),
        migrations.AddField(
            model_name='userapitokens',
            name='can_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userapitokens',
            name='can_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userapitokens',
            name='can_update',
            field=models.BooleanField(default=False),
        ),
    ]
