# Generated by Django 4.1.7 on 2023-05-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0004_userapitokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapitokens',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userapitokens',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
