# Generated by Django 4.1.7 on 2023-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0005_alter_userapitokens_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapitokens',
            name='generate_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
