# Generated by Django 4.1.7 on 2023-06-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0006_userapitokens_generate_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapitokens',
            name='generate_key',
            field=models.CharField(max_length=61, null=True),
        ),
    ]
