# Generated by Django 4.1.7 on 2023-05-17 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0006_alter_userapitokens_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapitokens',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 0, 6, 2, 215532)),
        ),
    ]
