# Generated by Django 4.1.7 on 2023-04-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercodes',
            name='totp_active',
            field=models.BooleanField(default=False),
        ),
    ]
