# Generated by Django 4.1.7 on 2023-05-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usersbackupcodes_codes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbackupcodes',
            name='codes_file',
            field=models.FileField(default=None, null=True, upload_to='codes/%Y-%m-%d/'),
        ),
    ]
