# Generated by Django 4.1.7 on 2023-04-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usercodes_totp_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercodes',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
