# Generated by Django 4.1.7 on 2023-04-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usersbackupcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersbackupcodes',
            name='generate_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersbackupcodes',
            name='codes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
