# Generated by Django 4.1.7 on 2023-04-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usersbackupcodes_generate_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersbackupcodes',
            old_name='codes_activate',
            new_name='codes_active',
        ),
    ]
